version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'
    networks:
      - tomatopay-network
  kafka:
    image: wurstmeister/kafka
    container_name: Kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "9092"]
      interval: 30s
      timeout: 10s
      retries: 4
    networks:
      - tomatopay-network
  dynamodb:
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    networks:
      - tomatopay-network
  mysql:
    image: mysql
    container_name: mysql-local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tomato_pay
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
      timeout: 20s
      retries: 10
    networks:
      - tomatopay-network
  domain-transaction-server:
    image: smudgal/pay-with-a-tomato:0.0.1
    container_name: dt-server
    ports:
      - '8080:8080'
    environment:
      MYSQL_HOST: mysql-local
      KAFKA_HOST: kafka
      DYNAMO_HOST: dynamodb-local
    depends_on:
      kafka:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - tomatopay-network

networks:
  tomatopay-network:
    driver: bridge