# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time

name: TomatoPay CICD

on:
  push:
    branches: [ $default-branch, develop ]
  pull_request:
    branches: [ $default-branch, develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - run: sudo service mysql start
      - run: mysql -uroot -proot -e 'create database tomato_pay'
      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v2.0.0
        with:
          port: 8000
          cors: '*'
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Publish to Docker Registry
          uses: elgohr/Publish-Docker-Github-Action@master
          with:
            name: smudgal/pay-with-a-tomato:0.0.1
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASS }}